version: '3.2'

services:

  consul:
    image: consul:1.7.3
    container_name: consul
    volumes:
      - consul_data:/consul/data
      - consul_config:/consul/config
    networks:
      - consul-vault 
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8501:8501'
      - '8600:8600'
      - '8600:8600/udp'
    command: agent -server -bootstrap -ui -client=0.0.0.0 -config-file=/consul/config/consul-config.json

volumes:
  consul_data:
  consul_config:

networks:
  consul-vault:
    driver: bridge
