version: '3.2'

services:
  
  web:
    image: 'gitlab/gitlab-ce:12.10.3-ce.0'
    container_name: gitlab
    restart: unless-stopped
    hostname: 'automatey.fritz.box'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://automatey.fritz.box'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
